### ISSUE TITLE
Issues with TPM

### ISSUE THREAD

**Issue by ggardet** [parallaxsecond/parsec#376] opened 2021-03-31 14:57 UTC
I am trying to setup PARSEC with a TPM module [0] on the Raspberry Pi 4.
I can get infos from the TPM with `eltt2` software but when I try to use the TPM module with PARSEC, I get the following error in the log:
```
mars 31 13:55:09 localhost parsec[2058]: [ERROR tss_esapi::context] Error while testing parameters: value is out of range or is not correct for the context (associated with parameter number 1).
```

`parsec-tool psa-generate-key -k "testTPM" -p 3` also fails with:
```
[INFO] Generating key...
[ERR] Executing subcommand failed.

Caused by:
    generic input/output error
```
And from the parsec log:
```
mars 31 14:52:31 localhost parsec[2058]: [ERROR parsec_service::front::front_end] Failed to send response;
```

Also, `parsec-tool  list-keys` returns:
```
[INFO] Available keys:
* 'testTPM' (MbedCrypto, 2048 bit RsaKeyPair)
```
which is weird as it claims it is from MbedCrypto, and previous command for TPM failed.

My current config is:
```
[core_settings]

[listener]
listener_type = "DomainSocket"
timeout = 200 # in milliseconds

[authenticator]
auth_type = "UnixPeerCredentials"

[[key_manager]]
name = "on-disk-manager"
manager_type = "OnDisk"

[[provider]]
provider_type = "MbedCrypto"
key_info_manager = "on-disk-manager"

[[provider]]
provider_type = "Tpm"
key_info_manager = "on-disk-manager"
tcti = "device:/dev/tpmrm0"
owner_hierarchy_auth = ""
```

[0]: https://buyzero.de/products/letstrust-hardware-tpm-trusted-platform-module

**Comment by ionut-arm** [comment] 2021-03-31 15:28
Hi 👋🏻 

I'll start from the top:

That `tss_esapi::context` error doesn't necessarily mean something wrong has happened - before we start our "main" TSS context we check whether we can use AES256 for session encryption. If it's not supported by the TPM, that error message you posted is logged and we fall back to AES128. I'll look at disabling logging for those calls, there's been a bit of confusion before because of them :) From the rest of the message I gather that the service did start correctly, it's just that one error log at the beginning.

We have seen that `generic input/output error` before, it was caused by timeouts - based on the command names, it looks like you're using version `0.1.0` of the tool. We increased the timeout in version `0.2.0` (and added a CLI option for it - `-t <number of seconds>`), using that or `0.3.0` is recommended.

As for the key being shown as belonging to the Mbed Crypto provider, that was a bug that we fixed in the (recently released) version `0.7.0` of the service! It's also recommended to switch to the new service version, but the bug is only "cosmetic" - the key is actually created in the correct provider by the tool - so switching over isn't crucial.

Let us know if this fixes your issues or if you hit new ones!

**Comment by ggardet** [comment] 2021-04-01 10:02
Updating to parsec-tool 0.3.0 fixes the issues, thanks a lot!

The only remaining error is the `tss_esapi::context` one, even with 0.7.2.

**Comment by ionut-arm** [comment] 2021-04-01 10:05
I'll try to have a "fix" for that one later today, though in truth it's not really an error, more like a misleading log message.

**Comment by ggardet** [comment] 2021-04-01 10:12
To be more precise, the error message is now:
```
parsec[8047]: [ERROR tss_esapi::context::tpm_commands::capability_commands] Error while testing parameters: value is out of range or is not correct for the context (associated with parameter number 1)
```

**Comment by hug-dev** [comment] 2021-04-08 14:22
@ionut-arm since #381 imported the latest `main` of `tss-esapi` that should be fixed, right?

**Comment by ionut-arm** [comment] 2021-04-08 14:25
I'd hope so!

**Comment by hug-dev** [comment] 2021-04-08 14:26
Ok closing for now then, but feel free to shout if it's still the same!

**Closed by hug-dev** 2021-04-08 14:26 UTC
Labels: bug, question
